name: Check for updates
on:
  schedule:
    - cron: "27 5 * * *"
permissions:
  contents: write
    
jobs:
  word_breaks:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install curl python3 python3-pip make
          pip3 install -r requirements.txt
      - name: Update word breaks and push
        run: |-
          make
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Updated unicode word breaks: ${timestamp}" || exit 0
          git push
